kind: Pod
apiVersion: v1
metadata:
  -name: evn

spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      # soft limit
      requests:
        memory: "68Mi"
        cpu: "100m"
      
      # hard limit
      limits:
        memory: "128Mi"
        cpu: "150m"   